### ISSUE TITLE
[management] set up issue template

### ISSUE THREAD

**Issue by andyzhangx** [csi-driver/azuredisk-csi-driver#26]
Could set up following 4 templates for new issues:
 - Bug report
Create a report to help us improve CSI Driver

 - Enhancement request
Suggest an idea for this project

 - Feature request
Suggest an idea for this project

 - Support request
Ask questions about the driver

**Comment by Masquerade0097** [comment]
Can I send a PR for this?

**Comment by andyzhangx** [comment]
@Masquerade0097 you could focus on sanity test first, I have assigned this task to @lizebang

**Comment by andyzhangx** [comment]
@Masquerade0097 If you have already figured out how to do this, you could send out a PR for this?

**Comment by lizebang** [comment]
@Masquerade0097 If you finish a part, we can finish it together.

**Comment by andyzhangx** [comment]
FYI. The https://github.com/csi-driver/azurefile-csi-driver project also needs such template

**Comment by Masquerade0097** [comment]
Yes, I have figured out how to do this. 

> @Masquerade0097 If you have already figured out how to do this, you could send out a PR for this?

The process to write different Issue templates is just the same. I have the PR ready.

> @Masquerade0097 If you finished a part, we can finish it together.

**Comment by andyzhangx** [comment]
@Masquerade0097 Great, then you could send the PR now.

**Comment by Masquerade0097** [comment]
Okay

**Comment by lizebang** [comment]
@andyzhangx @Masquerade0097 
Do we need to add labels into the templates?
Just like `Bug report`, if we change the header of [bug-report.md](https://github.com/csi-driver/azuredisk-csi-driver/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) to:
```markdown
---
name: Bug report
about: Create a report to help us improve CSI Driver
labels: bug
---
```
it will add `bug` label when create a `Bug report` issue.

**Comment by Masquerade0097** [comment]
@lizebang AFAIK The labels are for CLI bot, since we don't have the bot yet the `label` won't be needed.

**Comment by andyzhangx** [comment]
then can we set up the CLI bot?

**Comment by lizebang** [comment]
@Masquerade0097 Thanks a lot.

**Comment by andyzhangx** [comment]
I have made a new issue: set up the CLI bot https://github.com/csi-driver/azuredisk-csi-driver/issues/40

**Comment by Masquerade0097** [comment]
@andyzhangx I meant `k8s-ci-bot`, I made the correction in the above comment. Also, I guess that bot is added by maintainers. I'm not sure have to look up.

**Comment by andyzhangx** [comment]
@Masquerade0097 that's ok, let's see after this project is moved to k8s-sig, it's low priority.

**Comment by Masquerade0097** [comment]
Okay.

**Comment by lizebang** [comment]
@Masquerade0097 You are right.
@andyzhangx We can refer to [prow](https://github.com/kubernetes/test-infra/blob/ad64c1207e/prow/README.md) after this project is moved to k8s-sig.
