### ISSUE TITLE
[code refactor] switch glog to klog

### ISSUE THREAD

**Issue by andyzhangx** [csi-driver/azuredisk-csi-driver#41]
**Is your feature request related to a problem?/Why is this needed**
From kubernetes v1.13.x, `glog` is switched to `klog`, while our repo(depends on k8s v1.13.0 now) is still using `glog`, need to switch to use `klog`
https://github.com/csi-driver/azuredisk-csi-driver/blob/4215b94259b146ee1b8c3e9d7b4a2346b219f4a8/pkg/azurediskplugin/main.go#L46

**Describe the solution you'd like in detail**

**Describe alternatives you've considered**

**Additional context**

**Comment by ashishranjan738** [comment]
@andyzhangxI would like to work on it.

**Comment by andyzhangx** [comment]
sure, thanks

**Comment by andyzhangx** [comment]
it's already fixed
